# Generated by Django 6.0.1 on 2026-01-26 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_species', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='fishspecies',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_species_per_user'),
        ),
    ]
