# Generated by Django 6.0.1 on 2026-01-25 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PondFishStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_avg_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stocked_on', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pond')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fishspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FishSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_on', models.DateField()),
                ('sample_fish_count', models.PositiveIntegerField()),
                ('sample_total_weight', models.DecimalField(decimal_places=2, help_text='Total weight of sampled fish (grams)', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplings', to=settings.AUTH_USER_MODEL)),
                ('fish_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplings', to='sampling.pondfishstock')),
            ],
        ),
    ]
