# Generated by Django 6.0.1 on 2026-01-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondFishStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_avg_weight', models.DecimalField(decimal_places=2, help_text='Initial average weight per fish (grams)', max_digits=6)),
                ('stocked_on', models.DateField()),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_stocks', to='core.pond')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_stocks', to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='FishSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_on', models.DateField()),
                ('sample_fish_count', models.PositiveIntegerField()),
                ('sample_total_weight', models.DecimalField(decimal_places=2, help_text='Total weight of sampled fish (grams)', max_digits=7)),
                ('fish_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplings', to='sampling.pondfishstock')),
            ],
        ),
    ]
