# Generated by Django 6.0.1 on 2026-02-14 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_on', models.DateField()),
                ('sample_fish_count', models.PositiveIntegerField()),
                ('sample_total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fish_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplings', to='stock.pondfishstock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
