# Generated by Django 6.0.1 on 2026-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondfishstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total number of fish stocked initially'),
            preserve_default=False,
        ),
    ]
