# Generated by Django 6.0.1 on 2026-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtype',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
